[build]
  base = "light-version"
  command = "npm run build"
  publish = ".next"

[functions]
  included_files = ["database/light-news.db"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"

[context.production.environment]
  SITE_URL = "https://almukhtasar.netlify.app"
