import Link from "next/link";
import AdminControls from "@/components/AdminControls";
import { adminArticleQueue, adminDashboardSummary, categoryMonitoringRows, freshnessInventory, getSettings, listRuns, listSchedules, listSources, recentArticleSourceChecks, recentRetrievalLogs, rollingCoverageRows, schedulerHealth, sourceHealthRows, workflowSummary } from "@/database/database";

export const dynamic="force-dynamic";
function date(value:unknown){return value?new Date(String(value)).toLocaleString("ar-SA"):"—";}
function plain<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
export default function AdminPage(){
  const settings=getSettings(),sources=listSources(),summary=adminDashboardSummary(),scheduler=schedulerHealth(),freshness=freshnessInventory(),healthRows=plain(sourceHealthRows());
  const last=scheduler.lastFullRetrieval as Record<string,unknown>;
  const metrics=[['المصادر النشطة',summary.activeSources],['المصادر السليمة',summary.healthySources],['المصادر المتعثرة',summary.failingSources],['المسترجع اليوم',summary.retrievedToday],['المنشور اليوم',summary.publishedToday],['بانتظار المراجعة',summary.awaitingReview],['التكرارات الممنوعة',summary.duplicatesToday],['مشكلات الصور',summary.missingImages],['المهام الفاشلة',summary.failedJobs],['أرشفة اليوم',summary.archivedToday]];
  return <main className="admin-page"><div className="container"><header className="admin-heading"><div><span>لوحة العمليات</span><h1>إدارة الأخبار والمصادر</h1><p>تحكم كامل من تهيئة المصدر حتى النشر والمراقبة.</p></div><Link href="/">فتح الموقع ←</Link></header>
    <section className="admin-panel admin-overview"><div className="metric-grid operational">{metrics.map(([label,value])=><span className="metric" key={String(label)}><b>{String(value)}</b><small>{String(label)}</small></span>)}</div><div className="scheduler-strip"><span className={`health ${scheduler.healthy?'Healthy':'Degraded'}`}>حالة المجدول: {scheduler.healthy?'سليم':'مستحق للتحديث'}</span><span>حالة عمال المعالجة: {scheduler.workers}</span><span>آخر تحديث للمصادر: {date(last.finished_at)}</span><span>التحديث القادم: {date(scheduler.nextRetrieval)}</span></div><div className="metric-grid operational last-run-metrics"><span className="metric"><b>{String(last.sources_processed||0)}</b><small>عدد المصادر التي تم فحصها</small></span><span className="metric"><b>{String(last.discovered||0)}</b><small>الأخبار الجديدة المكتشفة</small></span><span className="metric"><b>{String(last.published||0)}</b><small>الأخبار المنشورة</small></span><span className="metric"><b>{String(last.duplicates||0)}</b><small>المكررات المستبعدة</small></span><span className="metric"><b>{String(last.failed_sources||0)}</b><small>المصادر المتعثرة</small></span><span className="metric"><b>{(Number(last.duration_ms||0)/1000).toFixed(1)}ث</b><small>مدة آخر عملية تحديث</small></span></div>{freshness.needsRecovery?<p className="evidence-note warning">توجد تصنيفات أو مخزونات حديثة دون الحد التشغيلي.</p>:null}</section>
    <section className="admin-panel"><h2>صحة استيراد الأخبار العاجلة</h2><p className="evidence-note">تعتمد الحالة على وصول المواد التي صنّفها المصدر نفسه كعاجلة، لا على كلمات العنوان.</p><div className="table-wrap"><table className="source-table"><thead><tr><th>المصدر</th><th>الحالة</th><th>آخر فحص</th><th>آخر اكتشاف</th><th>آخر استيراد</th><th>التأخير</th><th>عاجل اليوم</th></tr></thead><tbody>{healthRows.map((row)=><tr key={String(row.id)}><td>{String(row.name)}</td><td><b>{String(row.breaking_health||"Healthy")}</b></td><td>{date(row.last_breaking_check)}</td><td>{date(row.last_breaking_detected_at)}</td><td>{date(row.last_breaking_imported_at)}</td><td>{row.breaking_latency_seconds==null?"—":`${String(row.breaking_latency_seconds)}ث`}</td><td>{String(row.breaking_today||0)}</td></tr>)}</tbody></table></div></section>
  <AdminControls settings={settings} sources={sources} health={healthRows} runs={plain(listRuns(30))} logs={plain(recentRetrievalLogs(120))} sourceChecks={plain(recentArticleSourceChecks(120))} schedules={plain(listSchedules())} workflow={workflowSummary()} coverage={plain(categoryMonitoringRows())} dailyCoverage={plain(rollingCoverageRows())} review={plain(adminArticleQueue("review",50))} editorial={plain(adminArticleQueue("published",50))}/>
  </div></main>;
}
