import { NextRequest, NextResponse } from "next/server";
import { deleteRecord, getRecord, isAdminResource, updateRecord } from "@/lib/admin-db";
import { revalidatePath } from "next/cache";
import { recoverHomepageContent } from "@/lib/homepage-recovery";
export const runtime = "nodejs";

export async function GET(_: NextRequest, { params }: { params: Promise<{resource:string;id:string}> }) { const {resource,id}=await params;if(!isAdminResource(resource))return NextResponse.json({error:"RESOURCE_NOT_FOUND"},{status:404});const record=getRecord(resource,id);return record?NextResponse.json({data:record}):NextResponse.json({error:"NOT_FOUND"},{status:404}); }
export async function PATCH(request: NextRequest, { params }: { params: Promise<{resource:string;id:string}> }) { const {resource,id}=await params;if(!isAdminResource(resource))return NextResponse.json({error:"RESOURCE_NOT_FOUND"},{status:404});try{const body=await request.json(),current=getRecord(resource,id);let data=body.data;if(resource==="content"&&data&&typeof data==="object"&&Object.prototype.hasOwnProperty.call(data,"imageUrl")&&String(data.imageUrl||"")!==String(current?.data.imageUrl||""))data={...data,imageVerifiedAt:new Date().toISOString(),imageIsFallback:String(data.imageUrl||"").startsWith("/api/media/category-fallback/")};const record=updateRecord(resource,id,{title:body.title,status:body.status,data,restore:body.restore===true},request.headers.get("x-admin-user")||"مدير النظام");if(record&&resource==="content"){recoverHomepageContent(body.status==="معتمد"?"post_approved":"post_updated");revalidatePath("/");revalidatePath("/search");revalidatePath("/category/[slug]","page");revalidatePath("/archive","layout");revalidatePath("/news/[slug]","page");}return record?NextResponse.json({data:record}):NextResponse.json({error:"NOT_FOUND"},{status:404});}catch{return NextResponse.json({error:"INVALID_BODY"},{status:400});} }
export async function DELETE(request: NextRequest, { params }: { params: Promise<{resource:string;id:string}> }) { const {resource,id}=await params;if(!isAdminResource(resource))return NextResponse.json({error:"RESOURCE_NOT_FOUND"},{status:404});const deleted=deleteRecord(resource,id,request.headers.get("x-admin-user")||"مدير النظام");if(deleted&&resource==="content"){recoverHomepageContent("post_deleted_or_archived");revalidatePath("/");revalidatePath("/search");}return deleted?NextResponse.json({data:{archived:true}}):NextResponse.json({error:"NOT_FOUND"},{status:404}); }
