"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArchiveRestore, ChevronLeft, ChevronRight, Download, Edit3, Eye, ImageIcon, Loader2, Play, Plus, RefreshCw, Search, ShieldCheck, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { categoryFallbackUrl, embeddedCategoryFallback } from "@/lib/image-fallback";

type Field = { key:string; label:string; type?:"text"|"number"|"select"|"url"|"email"|"checkbox"|"textarea"; options?:string[]; required?:boolean; placeholder?:string };
type Config = { title:string; singular:string; description:string; fields:Field[]; columns:string[]; statuses:string[]; primaryAction?:string };
type RecordItem = { id:string; title:string; status:string; data:Record<string,unknown>; deleted:boolean; createdAt:string; updatedAt:string };
type RefreshRun = { status:string; startedAt:string; finishedAt:string; report:Record<string,unknown> };
type CategoryCoverage = {category:string;approved:number;eligible:number;connected:number;sources:Array<{name:string;status:string;trust:number;connected:boolean}>};
type HealthRow = {id:string;name:string;sourceType:string;retrievalMethod:string;categories:string[];lastChecked:string|null;lastSuccessfulConnection:string|null;lastArticleDiscovered:string|null;lastArticleRetrieved:string|null;lastPostPublished:string|null;recentItemsFound:number;imageRetrievalSuccess:number;averageProcessingTime:number|null;consecutiveFailures:number;healthStatus:string;healthReason:string;noRecentContent:boolean;isSocial:boolean};
type HealthSnapshot = {sources:HealthRow[];summary:{all:number;healthy:number;degraded:number;failing:number;social:number;noRecentContent:number};generatedAt:string};

const configurations:Record<string,Config> = {
  content:{title:"إدارة المحتوى",singular:"مادة",description:"الأخبار والمقالات والتقارير والتحليلات وجميع حالات النشر.",statuses:["مسودة","بانتظار المراجعة","بحاجة إلى مراجعة","بحاجة إلى تحقق","معتمد","مجدول","منشور","مؤرشف"],columns:["type","category","subcategory"],fields:[{key:"title",label:"العنوان",required:true},{key:"status",label:"الحالة",type:"select",options:["مسودة","بانتظار المراجعة","بحاجة إلى مراجعة","بحاجة إلى تحقق","معتمد","مجدول","منشور"]},{key:"type",label:"نوع المحتوى",type:"select",options:["خبر","خبر مستورد","مقال","تقرير","تحليل","فيديو","إنفوجرافيك"]},{key:"category",label:"التصنيف الرئيسي",required:true},{key:"subcategory",label:"التصنيف الفرعي"},{key:"author",label:"الكاتب"},{key:"language",label:"اللغة",type:"select",options:["العربية","English"]},{key:"summary",label:"باختصار (جملة أو جملتان)",type:"textarea"},{key:"details",label:"المضمون (تفاصيل جديدة فقط؛ افصل الفقرات بسطر فارغ)",type:"textarea"},{key:"validationErrors",label:"أسباب الحاجة إلى المراجعة",type:"textarea"},{key:"imageUrl",label:"صورة الخبر",type:"url"},{key:"imageAlt",label:"النص البديل للصورة"},{key:"imageCredit",label:"حقوق الصورة / المصدر"},{key:"featured",label:"خبر مميز",type:"checkbox"}]},
  sources:{title:"مصادر الأخبار",singular:"مصدر",description:"حوكمة المصادر والموصلات وسياسة الجلب والنشر مع سجل تشغيل قابل للتدقيق.",statuses:["نشط","متوقف","محظور","بانتظار الاعتماد"],columns:["tier","trust","updateFrequency"],primaryAction:"إضافة مصدر",fields:[{key:"title",label:"الاسم بالعربية",required:true},{key:"englishName",label:"الاسم بالإنجليزية"},{key:"status",label:"الحالة",type:"select",options:["نشط","متوقف","محظور","بانتظار الاعتماد"]},{key:"logoUrl",label:"رابط الشعار",type:"url"},{key:"url",label:"الموقع الرسمي",type:"url",required:true},{key:"type",label:"نوع المصدر",type:"select",options:["جهة حكومية رسمية","وكالة أنباء رسمية","قناة رسمية","صحيفة وطنية","قناة إخبارية","مصدر اقتصادي متخصص","صحيفة رياضية","مجلة متخصصة","RSS","Atom","News API","REST / JSON","منصة اجتماعية","مصدر يدوي"]},{key:"tier",label:"طبقة الموثوقية",type:"select",options:["رسمي حكومي","وكالة أنباء رسمية","صحافة وطنية معروفة","قناة رئيسية","متخصص معتمد","إقليمي معتمد","يدوي / غير رسمي"]},{key:"country",label:"الدولة"},{key:"language",label:"اللغة",type:"select",options:["العربية","English","متعدد"]},{key:"categories",label:"التصنيفات (مفصولة بفاصلة)"},{key:"geography",label:"النطاق الجغرافي"},{key:"contentTypes",label:"أنواع المحتوى"},{key:"trust",label:"درجة الموثوقية (0–100)",type:"number"},{key:"priority",label:"الأولوية (1 أعلى)",type:"number"},{key:"fetchMethod",label:"طريقة الجلب",type:"select",options:["صفحة أخبار رسمية","موقع إخباري","موقع / فيديو","RSS","Atom","REST / JSON","API","يدوي"]},{key:"feedUrl",label:"رابط RSS / Atom",type:"url"},{key:"apiUrl",label:"رابط API",type:"url"},{key:"xUrl",label:"حساب X الرسمي",type:"url"},{key:"youtubeUrl",label:"قناة YouTube الرسمية",type:"url"},{key:"updateFrequency",label:"معدل التحديث",type:"select",options:["كل 15 دقيقة","كل 30 دقيقة","كل ساعة","كل 3 ساعات","كل 6 ساعات","يوميًا","يدوي"]},{key:"maxItems",label:"الحد الأقصى لكل جلب",type:"number"},{key:"publicationMode",label:"وضع النشر الافتراضي",type:"select",options:["مسودة","مراجعة تحريرية","تحقق إلزامي","نشر آلي","استيراد دون نشر"]},{key:"sensitiveReview",label:"مراجعة بشرية للمحتوى الحساس",type:"checkbox"},{key:"copyrightMode",label:"سياسة حقوق النشر",type:"select",options:["ملخص أصلي ورابط المصدر","عنوان وملخص أصلي ورابط فقط","ملخص أصلي وتضمين مرخّص فقط","لا يُعاد استخدام الوسائط"]},{key:"mediaPolicy",label:"سياسة صور التغذية",type:"select",options:["استخدام صور التغذية مع الإسناد","عدم إعادة استخدام الوسائط"]},{key:"role",label:"دور المصدر في الدمج"},{key:"keywords",label:"الكلمات المفتاحية"},{key:"excludedWords",label:"الكلمات المستبعدة"},{key:"notes",label:"ملاحظات وقواعد خاصة",type:"textarea"}]},
  categories:{title:"التصنيفات",singular:"تصنيف",description:"التصنيفات الرئيسية والفرعية وترتيب ظهورها في الموقع.",statuses:["ظاهر","مخفي"],columns:["slug","parent","articles"],fields:[{key:"title",label:"اسم التصنيف",required:true},{key:"status",label:"الظهور",type:"select",options:["ظاهر","مخفي"]},{key:"slug",label:"الرابط المختصر",required:true},{key:"parent",label:"التصنيف الأب"},{key:"color",label:"اللون"},{key:"order",label:"الترتيب",type:"number"},{key:"description",label:"الوصف",type:"textarea"},{key:"menu",label:"إظهار في القائمة",type:"checkbox"}]},
  tags:{title:"الوسوم والكلمات المفتاحية",singular:"وسم",description:"إدارة الوسوم ودمج المتشابه ومنع التكرار.",statuses:["نشط","موقوف"],columns:["slug","articles"],fields:[{key:"title",label:"اسم الوسم",required:true},{key:"status",label:"الحالة",type:"select",options:["نشط","موقوف"]},{key:"slug",label:"الرابط المختصر",required:true},{key:"description",label:"الوصف",type:"textarea"}]},
  users:{title:"المستخدمون",singular:"مستخدم",description:"الحسابات الإدارية والأدوار والمصادقة الثنائية وآخر نشاط.",statuses:["نشط","معطل","دعوة معلقة"],columns:["email","role","lastLogin"],fields:[{key:"title",label:"الاسم",required:true},{key:"status",label:"الحالة",type:"select",options:["نشط","معطل","دعوة معلقة"]},{key:"email",label:"البريد",type:"email",required:true},{key:"role",label:"الدور",type:"select",options:["مدير النظام","رئيس التحرير","محرر","مراجع","مدقق حقائق","مسؤول مصادر","مسؤول SEO","مسؤول إعلانات"]},{key:"twoFactor",label:"فرض المصادقة الثنائية",type:"checkbox"}]},
  roles:{title:"الأدوار والصلاحيات",singular:"دور",description:"صلاحيات العرض والإضافة والتعديل والحذف والاعتماد والنشر.",statuses:["نشط","معطل"],columns:["users","permissions"],fields:[{key:"title",label:"اسم الدور",required:true},{key:"status",label:"الحالة",type:"select",options:["نشط","معطل"]},{key:"permissions",label:"الصلاحيات (مفصولة بفاصلة)",type:"textarea",required:true}]},
  reviews:{title:"المراجعة وتدقيق الحقائق",singular:"مراجعة",description:"المواد التي تحتاج قرارًا تحريريًا أو تحققًا من المعلومات.",statuses:["عاجل","قيد التحقق","مكتمل","مرفوض"],columns:["assignee","confidence","sources"],fields:[{key:"title",label:"عنوان المهمة",required:true},{key:"status",label:"الحالة",type:"select",options:["عاجل","قيد التحقق","مكتمل","مرفوض"]},{key:"assignee",label:"المراجع"},{key:"confidence",label:"درجة الثقة",type:"number"},{key:"sources",label:"عدد المصادر",type:"number"},{key:"evidence",label:"الأدلة والملاحظات",type:"textarea"}]},
  media:{title:"الوسائط والملفات",singular:"ملف",description:"الصور والفيديوهات والمستندات والنصوص البديلة وحالة الاستخدام.",statuses:["مستخدم","غير مستخدم","مؤرشف"],columns:["type","size","folder"],primaryAction:"إضافة ملف",fields:[{key:"title",label:"اسم الملف",required:true},{key:"status",label:"الحالة",type:"select",options:["مستخدم","غير مستخدم","مؤرشف"]},{key:"url",label:"رابط الملف",type:"url",required:true},{key:"type",label:"نوع MIME"},{key:"size",label:"الحجم"},{key:"folder",label:"المجلد"},{key:"alt",label:"النص البديل",required:true},{key:"description",label:"الوصف",type:"textarea"}]},
  seo:{title:"تحسين محركات البحث",singular:"إعداد SEO",description:"العناوين والأوصاف والفهرسة والروابط الأساسية والمشكلات.",statuses:["مكتمل","تحذير","خطأ"],columns:["score","canonical","issue"],fields:[{key:"title",label:"الصفحة",required:true},{key:"status",label:"الحالة",type:"select",options:["مكتمل","تحذير","خطأ"]},{key:"metaTitle",label:"عنوان SEO"},{key:"description",label:"الوصف التعريفي",type:"textarea"},{key:"canonical",label:"Canonical URL"},{key:"score",label:"درجة التحسين",type:"number"},{key:"index",label:"السماح بالفهرسة",type:"checkbox"}]},
  ads:{title:"الإعلانات",singular:"إعلان",description:"المساحات الإعلانية والاستهداف والفترات وإحصاءات الأداء.",statuses:["نشط","متوقف","مجدول","منتهي"],columns:["placement","device","ctr"],fields:[{key:"title",label:"اسم الإعلان",required:true},{key:"status",label:"الحالة",type:"select",options:["نشط","متوقف","مجدول","منتهي"]},{key:"placement",label:"موضع الظهور"},{key:"device",label:"الجهاز",type:"select",options:["الكل","سطح المكتب","الجوال"]},{key:"start",label:"تاريخ البداية"},{key:"end",label:"تاريخ النهاية"},{key:"code",label:"كود الإعلان",type:"textarea"}]},
  notifications:{title:"التنبيهات والإشعارات",singular:"إشعار",description:"إنشاء وجدولة واستهداف إشعارات الأخبار والتحديثات.",statuses:["مسودة","مجدول","مرسل","فشل"],columns:["channel","audience","scheduledAt"],fields:[{key:"title",label:"عنوان الإشعار",required:true},{key:"status",label:"الحالة",type:"select",options:["مسودة","مجدول","مرسل"]},{key:"channel",label:"القناة",type:"select",options:["Web Push","بريد إلكتروني","داخل الموقع"]},{key:"audience",label:"الجمهور"},{key:"scheduledAt",label:"موعد الإرسال"},{key:"body",label:"النص",type:"textarea",required:true},{key:"language",label:"اللغة",type:"select",options:["العربية","English"]}]},
  newsletters:{title:"النشرات البريدية",singular:"نشرة",description:"القوائم والقوالب والجدولة ومعدلات الفتح والنقر.",statuses:["مسودة","مجدول","مرسل","متوقف"],columns:["subscribers","frequency","nextSend"],fields:[{key:"title",label:"اسم النشرة",required:true},{key:"status",label:"الحالة",type:"select",options:["مسودة","مجدول","مرسل","متوقف"]},{key:"frequency",label:"التكرار",type:"select",options:["يومي","أسبوعي","شهري"]},{key:"nextSend",label:"الإرسال القادم"},{key:"subject",label:"عنوان البريد"},{key:"content",label:"محتوى النشرة",type:"textarea"}]},
  integrations:{title:"التكاملات",singular:"تكامل",description:"مزودو الأخبار والذكاء الاصطناعي والتحليلات والبريد والتخزين.",statuses:["متصل","غير متصل","خطأ","معطل"],columns:["provider","lastTest","attempts"],fields:[{key:"title",label:"اسم التكامل",required:true},{key:"status",label:"الحالة",type:"select",options:["متصل","غير متصل","معطل"]},{key:"provider",label:"المزود"},{key:"endpoint",label:"Endpoint",type:"url"},{key:"apiKey",label:"مفتاح API (يُحفظ مشفرًا)"},{key:"notes",label:"ملاحظات",type:"textarea"},{key:"secretConfigured",label:"المفتاح مضبوط",type:"checkbox"}]},
  policies:{title:"السياسات",singular:"سياسة",description:"سياسات الخصوصية والتحرير والتصحيح والذكاء الاصطناعي والأخبار الحساسة.",statuses:["مسودة","بانتظار المراجعة","منشور","مؤرشف"],columns:["language","version","updatedBy"],fields:[{key:"title",label:"اسم السياسة",required:true},{key:"status",label:"الحالة",type:"select",options:["مسودة","بانتظار المراجعة","منشور","مؤرشف"]},{key:"language",label:"اللغة",type:"select",options:["العربية","English"]},{key:"version",label:"رقم الإصدار",type:"number"},{key:"content",label:"نص السياسة",type:"textarea",required:true}]},
  jobs:{title:"المهام المجدولة والأتمتة",singular:"مهمة",description:"مهام الجلب والتلخيص والتصنيف والترجمة والنشر.",statuses:["نشط","متوقف","يعمل الآن","فشل"],columns:["schedule","nextRun","successRate"],fields:[{key:"title",label:"اسم المهمة",required:true},{key:"status",label:"الحالة",type:"select",options:["نشط","متوقف"]},{key:"schedule",label:"Cron expression",required:true},{key:"type",label:"نوع المهمة",type:"select",options:["جلب","تلخيص","تصنيف","ترجمة","نشر","نشرة"]},{key:"source",label:"المصدر أو التصنيف"}]},
  archives:{title:"إدارة الأرشيف",singular:"مجموعة أرشيف",description:"الأخبار المؤرشفة حسب التاريخ وإمكانية الاستعادة.",statuses:["متاح","مؤرشف","محذوف"],columns:["year","month","articles"],fields:[{key:"title",label:"اسم المجموعة",required:true},{key:"status",label:"الحالة",type:"select",options:["متاح","مؤرشف"]},{key:"year",label:"السنة",type:"number"},{key:"month",label:"الشهر",type:"number"}]},
  backups:{title:"النسخ الاحتياطي والاستعادة",singular:"نسخة احتياطية",description:"نسخ قاعدة البيانات والملفات والإعدادات والتحقق من السلامة.",statuses:["قيد الإنشاء","سليمة","فشل"],columns:["type","size","createdAt"],primaryAction:"إنشاء نسخة",fields:[{key:"title",label:"اسم النسخة",required:true},{key:"status",label:"الحالة",type:"select",options:["قيد الإنشاء","سليمة","فشل"]},{key:"type",label:"النطاق",type:"select",options:["قاعدة البيانات","الملفات","الإعدادات","نسخة كاملة"]},{key:"destination",label:"وجهة التخزين"}]}
};

configurations.sources.fields.push(
  {key:"subcategories",label:"التصنيفات الفرعية (مفصولة بفاصلة)"},
  {key:"socialAccountId",label:"معرّف الحساب الاجتماعي"},
  {key:"instagramUrl",label:"حساب Instagram الرسمي",type:"url"},
  {key:"facebookUrl",label:"صفحة Facebook الرسمية",type:"url"},
  {key:"linkedinUrl",label:"حساب LinkedIn الرسمي",type:"url"},
  {key:"tiktokUrl",label:"حساب TikTok الرسمي",type:"url"},
  {key:"threadsUrl",label:"حساب Threads الرسمي",type:"url"},
  {key:"telegramUrl",label:"قناة Telegram الرسمية",type:"url"},
  {key:"snapchatUrl",label:"حساب Snapchat الرسمي",type:"url"},
  {key:"automaticPublishingPermission",label:"السماح بالنشر الآلي",type:"checkbox"}
  ,{key:"articleUrlPattern",label:"نمط روابط المقالات (Regex)"}
  ,{key:"headlineSelector",label:"محدد CSS للعنوان"}
  ,{key:"bodySelector",label:"محدد CSS لمتن المقال"}
  ,{key:"publicationDateSelector",label:"محدد CSS لتاريخ النشر"}
  ,{key:"featuredImageSelector",label:"محدد CSS للصورة الرئيسية"}
  ,{key:"canonicalSelector",label:"محدد CSS للرابط الأساسي"}
  ,{key:"categoryMap",label:"خريطة التصنيفات (JSON)",type:"textarea"}
  ,{key:"excludedUrlPatterns",label:"أنماط الروابط المستبعدة",type:"textarea"}
  ,{key:"maxPages",label:"الحد الأقصى للصفحات",type:"number"}
  ,{key:"requestsPerMinute",label:"طلبات الموصل في الدقيقة",type:"number"}
  ,{key:"retryAttempts",label:"عدد محاولات الاستعادة",type:"number"}
);
if(!configurations.content.statuses.includes("احتياطي"))configurations.content.statuses.splice(-1,0,"احتياطي");
const contentStatusField=configurations.content.fields.find((field)=>field.key==="status");
if(contentStatusField?.options&&!contentStatusField.options.includes("احتياطي"))contentStatusField.options.splice(-1,0,"احتياطي");

export default function ResourceManager({ resource, onNotify }: { resource:string; onNotify?:(message:string)=>void }) {
  const router=useRouter();
  const config=configurations[resource] || configurations.content;
  const [items,setItems]=useState<RecordItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("الكل"),[page,setPage]=useState(1),[pages,setPages]=useState(1),[showArchived,setShowArchived]=useState(false);
  const [editor,setEditor]=useState<RecordItem|null|"new">(null),[confirmDelete,setConfirmDelete]=useState<RecordItem|null>(null),[saving,setSaving]=useState(false);
  const [refreshRun,setRefreshRun]=useState<RefreshRun|null>(null),[refreshingSources,setRefreshingSources]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/admin/${resource}?q=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}&page=${page}&deleted=${showArchived}`);if(!response.ok)throw new Error();const result=await response.json();setItems(result.data);setPages(result.meta.pages||1);}catch{setError("تعذر تحميل البيانات. حاول مرة أخرى.");}finally{setLoading(false)}},[resource,search,status,page,showArchived]);
  useEffect(()=>{const timer=window.setTimeout(load,180);return()=>window.clearTimeout(timer)},[load]);
  const displayColumns=useMemo(()=>config.columns.slice(0,3),[config.columns]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget),data:Record<string,unknown>={};for(const field of config.fields){if(field.key==="title"||field.key==="status")continue;const raw=field.type==="checkbox"?form.get(field.key)==="on":form.get(field.key);data[field.key]=field.type==="number"&&raw!==""?Number(raw):raw;}const body={title:String(form.get("title")||""),status:String(form.get("status")||"نشط"),data};try{const isNew=editor==="new";const response=await fetch(isNew?`/api/admin/${resource}`:`/api/admin/${resource}/${(editor as RecordItem).id}`,{method:isNew?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){const result=await response.json();throw new Error(result?.fields?.title||"تعذر الحفظ");}setEditor(null);onNotify?.(isNew?`تمت إضافة ${config.singular} بنجاح`:`تم تحديث ${config.singular} بنجاح`);await load();}catch(error){setError(error instanceof Error?error.message:"تعذر الحفظ");}finally{setSaving(false)}}
  async function archive(){if(!confirmDelete)return;const response=await fetch(`/api/admin/${resource}/${confirmDelete.id}`,{method:"DELETE"});if(response.ok){onNotify?.(`تمت أرشفة ${config.singular}`);setConfirmDelete(null);load();}else setError("تعذر تنفيذ الإجراء");}
  async function restore(item:RecordItem){const response=await fetch(`/api/admin/${resource}/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({restore:true})});if(response.ok){onNotify?.(`تمت استعادة ${config.singular}`);load();}}
  async function refreshSources(sourceId?:string,category?:string,workflow:"publish"|"review"="publish"){setRefreshingSources(true);setError("");try{const response=await fetch("/api/admin/sources/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sourceId,category,workflow,triggerType:"manual"}),cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result?.error||"تعذر تشغيل التحديث");setRefreshRun(result.data);const report=result.data.report;const missing=Array.isArray(report.uncoveredCategories)?report.uncoveredCategories.length:0;onNotify?.(missing?`اكتمل التحديث بتحذير: ${missing} تصنيف دون مواد مطابقة · ${report.published||0} منشور`:`تم التحديث: ${report.published||0} منشور، ${report.invalidForReview||0} غير مكتمل للمراجعة، ${report.sensitiveForReview||0} حساس للمراجعة`);await load();router.refresh();window.dispatchEvent(new CustomEvent("almukhtasar-news-updated",{detail:report}));}catch(error){setError(error instanceof Error?error.message:"تعذر تشغيل التحديث");}finally{setRefreshingSources(false);}}
  async function testConnection(item:RecordItem){setLoading(true);try{const response=await fetch("/api/admin/test-connection",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,id:item.id})});const result=await response.json();if(!response.ok)throw new Error(result.error==="INVALID_OR_PRIVATE_URL"?"أضف رابطًا خارجيًا صالحًا قبل الاختبار":"فشل اختبار الاتصال");onNotify?.(`نجح اختبار الاتصال خلال ${result.latencyMs||0}ms`);}catch(error){setError(error instanceof Error?error.message:"تعذر تنفيذ الاختبار");}finally{load();}}
  async function quickAction(item:RecordItem){if(resource==="sources"){await refreshSources(item.id);return;}if(resource==="categories"){await refreshSources(undefined,item.title);return;}setLoading(true);try{if(["notifications","newsletters"].includes(resource)){const response=await fetch(`/api/admin/${resource}/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"مرسل",data:{sentAt:new Date().toISOString()}})});if(!response.ok)throw new Error("فشل الإرسال");onNotify?.(resource==="notifications"?"تم تسجيل إرسال الإشعار":"تم تسجيل إرسال النشرة");}else{await testConnection(item);onNotify?.(resource==="jobs"?"بدأ تشغيل المهمة":"نجح اختبار الاتصال");}}catch(error){setError(error instanceof Error?error.message:"تعذر تنفيذ الاختبار");}finally{load();}}
  function exportCsv(){const rows=[["العنوان","الحالة",...displayColumns],...items.map(item=>[item.title,item.status,...displayColumns.map(key=>formatValue(item.data[key]))])];const blob=new Blob(["\uFEFF"+rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`${resource}.csv`;anchor.click();URL.revokeObjectURL(url);}
  const editing=editor&&editor!=="new"?editor:null;
  return <section className="resource-workspace"><header className="resource-heading"><div><h2>{config.title}</h2><p>{config.description}</p></div><div>{resource==="sources"&&<button className="source-refresh-btn" disabled={refreshingSources} onClick={()=>refreshSources()} aria-live="polite">{refreshingSources?<Loader2 className="spin"/>:<RefreshCw/>} {refreshingSources?"جارٍ جلب الأخبار والصور...":"تحديث الأخبار الآن"}</button>}<button className="secondary-admin-btn" onClick={exportCsv}><Download/> تصدير CSV</button><button className="primary-btn" onClick={()=>setEditor("new")}><Plus/> {config.primaryAction||`إضافة ${config.singular}`}</button></div></header>
    <div className="resource-toolbar"><label className="resource-search"><Search/><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder={`بحث في ${config.title}...`}/></label><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option>الكل</option>{config.statuses.map(item=><option key={item}>{item}</option>)}</select><label className="archived-toggle"><input type="checkbox" checked={showArchived} onChange={event=>{setShowArchived(event.target.checked);setPage(1)}}/> عرض المؤرشف</label><button className="icon-admin-btn" onClick={load} aria-label="تحديث"><RefreshCw/></button></div>
    {error&&<div className="admin-error"><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}
    {resource==="sources"&&<SourceGovernance run={refreshRun} refreshSources={refreshSources}/>} 
    <div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>{config.singular}</th><th>الحالة</th>{displayColumns.map(column=><th key={column}>{labelFor(config,column)}</th>)}<th>آخر تحديث</th><th>الإجراءات</th></tr></thead><tbody>{loading?<tr><td colSpan={7}><div className="resource-state"><Loader2 className="spin"/> جارٍ التحميل...</div></td></tr>:!items.length?<tr><td colSpan={7}><div className="resource-state"><Eye/><strong>لا توجد نتائج</strong><small>غيّر عوامل البحث أو أضف عنصرًا جديدًا.</small></div></td></tr>:items.map(item=><tr key={item.id}><td><div className="resource-title-cell">{resource==="content"&&<ContentThumbnail item={item}/>}<span><strong>{item.title}</strong><small>{resource==="sources"?String(item.data.role||item.data.type||""):resource==="content"?String(item.data.imageCredit||`#${item.id.slice(0,8)}`):`#${item.id.slice(0,8)}`}</small></span></div></td><td><span className={`resource-status ${statusClass(item.status)}`}>{item.status}</span></td>{displayColumns.map(column=><td key={column}>{formatValue(item.data[column])}</td>)}<td><time>{String(item.data.lastSuccess?new Date(String(item.data.lastSuccess)).toLocaleString("ar-SA"):new Date(item.updatedAt).toLocaleDateString("ar-SA"))}</time></td><td><div className="row-actions">{resource==="sources"&&!showArchived&&<button title="اختبار الاتصال" onClick={()=>testConnection(item)}><ShieldCheck/></button>}{["sources","integrations","jobs","notifications","newsletters"].includes(resource)&&!showArchived&&<button title={resource==="sources"?"تحديث هذا المصدر":resource==="notifications"||resource==="newsletters"?"إرسال الآن":"اختبار أو تشغيل"} onClick={()=>quickAction(item)}>{resource==="sources"?<RefreshCw/>:<Play/>}</button>}<button title="تعديل" onClick={()=>setEditor(item)}><Edit3/></button>{showArchived?<button title="استعادة" onClick={()=>restore(item)}><ArchiveRestore/></button>:<button className="danger" title="أرشفة" onClick={()=>setConfirmDelete(item)}><Trash2/></button>}</div></td></tr>)}</tbody></table></div>
    <footer className="resource-pagination"><span>صفحة {page} من {Math.max(pages,1)}</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronRight/></button><button disabled={page>=pages} onClick={()=>setPage(page+1)}><ChevronLeft/></button></div></footer>
    {editor&&<div className="admin-modal-backdrop" role="presentation"><div className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="resource-modal-title"><header><div><h2 id="resource-modal-title">{editor==="new"?`إضافة ${config.singular}`:`تعديل ${config.singular}`}</h2><p>الحقول المعلّمة مطلوبة للحفظ.</p></div><button onClick={()=>setEditor(null)} aria-label="إغلاق"><X/></button></header><form onSubmit={submit}><div className="resource-form-grid">{config.fields.map(field=><FormField field={field} key={field.key} item={editing}/>)}</div><footer><button type="button" onClick={()=>setEditor(null)}>إلغاء</button><button className="primary-btn" disabled={saving}>{saving?<Loader2 className="spin"/>:null} حفظ التغييرات</button></footer></form></div></div>}
    {confirmDelete&&<div className="admin-modal-backdrop"><div className="confirm-dialog" role="alertdialog" aria-modal="true"><span><Trash2/></span><h2>أرشفة «{confirmDelete.title}»؟</h2><p>يمكن استعادة العنصر لاحقًا من خيار «عرض المؤرشف».</p><div><button onClick={()=>setConfirmDelete(null)}>إلغاء</button><button className="danger-confirm" onClick={archive}>تأكيد الأرشفة</button></div></div></div>}
  </section>;
}

function SourceGovernance({run,refreshSources}:{run:RefreshRun|null;refreshSources:(sourceId?:string,category?:string,workflow?:"publish"|"review")=>Promise<void>}){
  const report=run?.report||{};
  const [coverage,setCoverage]=useState<CategoryCoverage[]>([]),[health,setHealth]=useState<HealthSnapshot|null>(null),[healthFilter,setHealthFilter]=useState("all"),[selected,setSelected]=useState<{source:RecordItem;state:Record<string,unknown>|null;items:Array<Record<string,unknown>>}|null>(null),[healthBusy,setHealthBusy]=useState("");
  const loadHealth=useCallback(()=>fetch("/api/admin/sources/health",{cache:"no-store"}).then((response)=>response.ok?response.json():null).then((result)=>{if(result?.data)setHealth(result.data)}).catch(()=>undefined),[]);
  useEffect(()=>{fetch("/api/admin/sources/coverage").then((response)=>response.ok?response.json():null).then((result)=>{if(result?.data)setCoverage(result.data)}).catch(()=>undefined);loadHealth()},[run,loadHealth]);
  async function operation(sourceId:string,action:"pause"|"activate"|"change-method",method?:string){setHealthBusy(`${sourceId}:${action}`);try{await fetch(`/api/admin/sources/${sourceId}/operations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,method})});await loadHealth()}finally{setHealthBusy("")}}
  async function inspect(sourceId:string){setHealthBusy(`${sourceId}:inspect`);try{const response=await fetch(`/api/admin/sources/${sourceId}/operations`,{cache:"no-store"}),result=await response.json();if(response.ok)setSelected(result.data)}finally{setHealthBusy("")}}
  const visible=(health?.sources||[]).filter((source)=>healthFilter==="all"||healthFilter==="healthy"?healthFilter!=="healthy"||source.healthStatus==="Healthy":healthFilter==="degraded"?source.healthStatus==="Degraded":healthFilter==="failing"?["Failing","Authentication Required","Rate Limited","Configuration Error"].includes(source.healthStatus):healthFilter==="social"?source.isSocial:source.noRecentContent);
  return <div className="source-governance">
    <div className="source-policy-strip"><ShieldCheck/><div><strong>قاعدة الدمج والنشر</strong><p>واس للبيانات الرسمية المكتوبة، والإخبارية للبث والمقابلات. السياسة والأمن والصحة والقانون والحوادث تمر دائمًا بمراجعة بشرية، ولا يُنسخ النص الكامل من المصدر.</p></div></div>
    {health&&<section className="source-health-dashboard"><header><div><strong>مراقبة صحة المصادر</strong><small>الحالة التشغيلية مبنية على الاتصال والجلب والمواد الحديثة والصور، وليست على حالة «نشط» فقط.</small></div><button disabled={Boolean(healthBusy)} onClick={async()=>{setHealthBusy("all");await refreshSources(undefined,undefined,"review");await loadHealth();setHealthBusy("")}}>{healthBusy==="all"?<Loader2 className="spin"/>:<ShieldCheck/>} اختبار جميع المصادر</button></header>
      <nav>{([["all","الكل",health.summary.all],["healthy","سليمة",health.summary.healthy],["degraded","متدهورة",health.summary.degraded],["failing","فاشلة",health.summary.failing],["social","اجتماعية",health.summary.social],["stale","لا محتوى حديث",health.summary.noRecentContent]] as Array<[string,string,number]>).map(([key,label,count])=><button key={key} className={healthFilter===key?"active":""} onClick={()=>setHealthFilter(key)}>{label}<b>{count}</b></button>)}</nav>
      <div className="source-health-table"><table><thead><tr><th>المصدر</th><th>الموصل والتصنيفات</th><th>آخر نجاح / مادة</th><th>العناصر والصور</th><th>الأداء والفشل</th><th>الصحة</th><th>الإجراءات</th></tr></thead><tbody>{visible.map((source)=><tr key={source.id}><td><strong>{source.name}</strong><small>{source.sourceType}</small></td><td><b>{source.retrievalMethod}</b><small>{source.categories.join("، ")||"غير معيّن"}</small></td><td><b>{formatHealthDate(source.lastSuccessfulConnection)}</b><small>آخر مادة: {formatHealthDate(source.lastArticleRetrieved)}</small></td><td><b>{source.recentItemsFound} حديث</b><small>نجاح الصور {source.imageRetrievalSuccess}%</small></td><td><b>{source.averageProcessingTime===null?"—":`${source.averageProcessingTime}ms`}</b><small>{source.consecutiveFailures} فشل متتالٍ</small></td><td><span className={`health-badge health-${source.healthStatus.toLowerCase().replaceAll(" ","-")}`}>{healthArabic(source.healthStatus)}</span><small title={source.healthReason}>{source.healthReason}</small></td><td><div className="health-actions">{!source.isSocial&&<><button disabled={Boolean(healthBusy)} onClick={async()=>{setHealthBusy(`${source.id}:test`);await refreshSources(source.id,undefined,"review");await loadHealth();setHealthBusy("")}}>اختبار المصدر</button><button disabled={Boolean(healthBusy)} onClick={()=>refreshSources(source.id)}>جلب الآن</button><button disabled={Boolean(healthBusy)} onClick={()=>inspect(source.id)}>أحدث المواد / الأخطاء</button><select aria-label="تغيير طريقة الجلب" defaultValue="" onChange={(event)=>{if(event.target.value)operation(source.id,"change-method",event.target.value);event.target.value=""}}><option value="">تغيير طريقة الجلب</option><option>API</option><option>RSS</option><option>Atom</option><option>صفحة أخبار رسمية</option><option>موقع إخباري</option></select><button onClick={()=>operation(source.id,source.healthStatus==="Paused"?"activate":"pause")}>{source.healthStatus==="Paused"?"تفعيل":"إيقاف"}</button>{source.consecutiveFailures>0&&<button onClick={()=>refreshSources(source.id)}>إعادة الفاشل</button>}</>}</div></td></tr>)}</tbody></table></div>
      {selected&&<div className="health-inspector"><header><div><strong>{selected.source.title}</strong><small>{String(selected.state?.lastError||"لا توجد أخطاء مسجلة")}</small></div><button onClick={()=>setSelected(null)}>×</button></header><div>{selected.items.length?selected.items.map((item)=><article key={String(item.id)}><span><b>{String(item.title)}</b><small>{String(item.category||"")} · {String(item.status||"")}</small></span>{item.url?<a href={String(item.url)} target="_blank" rel="noreferrer">المصدر الأصلي</a>:null}</article>):<p>لم تُسترجع مواد من هذا المصدر بعد.</p>}</div></div>}
    </section>}
    {coverage.length>0&&<section className="category-source-coverage"><header><div><strong>تغطية المصادر حسب التصنيف</strong><small>لا يدخل خط التحديث إلا المصدر النشط والمعتمد والموثوق والمرتبط بالتصنيف.</small></div><span>{coverage.filter((item)=>item.connected>0).length}/{coverage.length} مكتمل</span></header><div>{coverage.map((item)=><article key={item.category} className={item.connected>0&&item.eligible>0?"covered":"missing"}><span><b>{item.category}</b><small>{item.eligible} معتمد · {item.connected} متصل</small></span><div>{item.sources.slice(0,3).map((source)=><em key={source.name} title={`${source.trust}% · ${source.status}`}>{source.name}</em>)}</div></article>)}</div></section>}
    {run&&<section className="refresh-report" aria-live="polite"><header><div><strong>تقرير آخر تحديث</strong><small>{new Date(run.finishedAt).toLocaleString("ar-SA")} · {run.status}</small></div><span>{String(report.sourcesChecked||0)} مصدرًا فُحص</span></header><div className="refresh-metrics"><span><b>{String(report.imported||0)}</b>جديد</span><span><b>{String(report.updated||0)}</b>محدّث</span><span><b>{String(report.imagesImported||0)}</b>بصورة أصلية</span><span><b>{String(report.fallbackImages||0)}</b>بصورة افتراضية</span><span><b>{String(report.duplicates||0)}</b>مكرر/مستبعد</span><span><b>{String(report.review||0)}</b>للمراجعة</span><span><b>{String(report.drafts||0)}</b>مسودة</span><span><b>{String(report.failed||0)}</b>فشل</span><span><b>{String(report.skipped||0)}</b>مستبعد</span></div>{Array.isArray(report.uncoveredCategories)&&report.uncoveredCategories.length>0&&<p className="refresh-warning">لم تصل مواد مطابقة في هذه الجولة: {(report.uncoveredCategories as string[]).join("، ")}</p>}{Boolean(report.categories)&&typeof report.categories==="object"&&<div className="category-refresh-results">{Object.entries(report.categories as Record<string,Record<string,unknown>>).map(([category,result])=><span key={category}><b>{category}</b><small>{String(result.imported||0)} جديد · {String(result.updated||0)} محدّث · {String(result.fetched||0)} مصنّف</small></span>)}</div>}{Array.isArray(report.details)&&<details><summary>تفاصيل المصادر والأسباب</summary><ul>{(report.details as Array<Record<string,unknown>>).map((item,index)=><li key={`${item.sourceId||index}`}><b>{String(item.name||"")}</b><span>{String(item.status||"")}{item.message?` — ${String(item.message)}`:""}</span></li>)}</ul></details>}</section>}
  </div>;
}

function healthArabic(status:string){return ({Healthy:"سليم",Degraded:"متدهور",Failing:"فاشل","Authentication Required":"يتطلب مصادقة","Rate Limited":"محدود المعدل","Configuration Error":"خطأ إعداد",Paused:"متوقف"} as Record<string,string>)[status]||status}
function formatHealthDate(value:string|null){return value?new Date(value).toLocaleString("ar-SA",{dateStyle:"short",timeStyle:"short"}):"لم يحدث"}

export function TabbedResources({tabs,onNotify}:{tabs:Array<{resource:string;label:string}>;onNotify?:(message:string)=>void}){const [active,setActive]=useState(tabs[0].resource);return <div><div className="resource-tabs">{tabs.map(tab=><button key={tab.resource} className={active===tab.resource?"active":""} onClick={()=>setActive(tab.resource)}>{tab.label}</button>)}</div><ResourceManager resource={active} onNotify={onNotify}/></div>}

function FormField({field,item}:{field:Field;item:RecordItem|null}){const value=field.key==="title"?item?.title:field.key==="status"?item?.status:item?.data[field.key];const className=field.type==="textarea"?"full-field":"";return <label className={className}><span>{field.label}{field.required&&<b>*</b>}</span>{field.type==="select"?<select name={field.key} defaultValue={String(value||field.options?.[0]||"")} required={field.required}>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:field.type==="textarea"?<textarea name={field.key} defaultValue={String(value||"")} rows={4} required={field.required}/>:field.type==="checkbox"?<input name={field.key} type="checkbox" defaultChecked={Boolean(value)}/>:<input name={field.key} type={field.type||"text"} defaultValue={String(value??"")} required={field.required} placeholder={field.placeholder}/>}</label>}
function ContentThumbnail({item}:{item:RecordItem}){const stored=typeof item.data.imageUrl==="string"?item.data.imageUrl:"",imported=item.data.type==="خبر مستورد"&&typeof item.data.originalUrl==="string"&&item.data.originalUrl,category=String(item.data.category||"عام"),fallback=imported?categoryFallbackUrl(category):"",primary=item.data.imageIsFallback===true?stored:imported?`/api/media/source-image/${item.id}`:stored;const [failed,setFailed]=useState(false),[fallbackFailed,setFallbackFailed]=useState(false),src=fallbackFailed?embeddedCategoryFallback(category):failed?(fallback||embeddedCategoryFallback(category)):(primary||fallback);useEffect(()=>{setFailed(false);setFallbackFailed(false)},[primary,fallback]);return src?<img src={src} alt={failed||fallbackFailed?`صورة افتراضية لتصنيف ${category}`:String(item.data.imageAlt||item.title)} referrerPolicy="no-referrer" loading="lazy" onError={()=>{if(fallbackFailed)return;if(failed||src===fallback)setFallbackFailed(true);else setFailed(true)}}/>:<span className="resource-thumbnail-placeholder" title="لا توجد صورة متاحة"><ImageIcon/></span>}
function labelFor(config:Config,key:string){return config.fields.find(field=>field.key===key)?.label||key;}
function formatValue(value:unknown){if(Array.isArray(value))return value.join("، ");if(typeof value==="boolean")return value?"نعم":"لا";if(value===undefined||value===null||value==="")return "—";return String(value);}
function statusClass(status:string){if(["نشط","منشور","معتمد","متصل","مكتمل","سليمة","ظاهر","متاح","مرسل"].includes(status))return"positive";if(["خطأ","محظور","فشل","مرفوض"].includes(status))return"negative";if(["مسودة","متوقف","معطل","مؤرشف","غير متصل"].includes(status))return"neutral";return"warning";}
