"use client";

import { useCallback, useEffect, useState } from "react";
import { CalendarClock, Loader2, Play, Plus, RefreshCw, Trash2 } from "lucide-react";

type Schedule={id:string;name:string;enabled:boolean;targetType:string;targetId:string|null;frequency:string;intervalHours:number;fixedTime:string;weekdays:number[];timezone:string;workflow:string;nextRunAt:string|null;lastRunAt:string|null};
type Run={id:string;triggerType:string;targetType:string;status:string;actor:string;report:Record<string,unknown>;error:string;startedAt:string;finishedAt:string|null;durationMs:number|null};
type Option={id:string;title:string};
type SourceHealth={sourceId:string;adapter:string;retrievalMethod:string;healthStatus:string;consecutiveFailures:number;lastCheckedAt:string|null;lastSuccessAt:string|null;lastArticleAt:string|null;responseTimeMs:number|null;articlesFound:number;articlesAccepted:number;articlesRejected:number;extractionFailures:number;imageFailures:number;httpErrors:number;lastError:string};
const days=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
const empty={name:"جدول جلب جديد",enabled:true,targetType:"news",targetId:"",frequency:"hourly",intervalHours:1,fixedTime:"00:00",weekdays:[] as number[],timezone:"Asia/Riyadh",workflow:"review"};

export default function RetrievalAutomation({onNotify}:{onNotify?:(message:string)=>void}){
  const [schedules,setSchedules]=useState<Schedule[]>([]),[runs,setRuns]=useState<Run[]>([]),[sources,setSources]=useState<Option[]>([]),[categories,setCategories]=useState<Option[]>([]),[health,setHealth]=useState<SourceHealth[]>([]),[form,setForm]=useState(empty),[quickSource,setQuickSource]=useState(""),[quickCategory,setQuickCategory]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{try{const [scheduleResponse,runResponse,sourceResponse,categoryResponse,healthResponse]=await Promise.all([fetch("/api/admin/retrieval/schedules",{cache:"no-store"}),fetch("/api/admin/retrieval/runs",{cache:"no-store"}),fetch("/api/admin/sources?limit=100",{cache:"no-store"}),fetch("/api/admin/categories?limit=100",{cache:"no-store"}),fetch("/api/admin/retrieval/health",{cache:"no-store"})]);setSchedules((await scheduleResponse.json()).data||[]);setRuns((await runResponse.json()).data||[]);setSources(((await sourceResponse.json()).data||[]).map((item:Option)=>({id:item.id,title:item.title})));setCategories(((await categoryResponse.json()).data||[]).map((item:Option)=>({id:item.title,title:item.title})));setHealth(((await healthResponse.json()).data||{}).sources||[]);}catch{setError("تعذر تحميل إعدادات الأتمتة.");}},[]);
  useEffect(()=>{void load();},[load]);
  async function manual(targetType:string,targetId?:string,workflow="publish"){setBusy(`run:${targetType}:${targetId||""}`);setError("");try{const response=await fetch("/api/admin/retrieval/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetType,targetId,workflow})});const result=await response.json();if(!response.ok)throw new Error(result.error||"تعذر تشغيل الجلب");const report=result.data?.news?.data?.report||result.data?.news?.report||{};onNotify?.(`اكتملت جلسة الجلب: ${report.published||0} منشور، ${report.invalidForReview||0} غير مكتمل للمراجعة، ${report.sensitiveForReview||0} حساس للمراجعة.`);await load();}catch(value){setError(value instanceof Error?value.message:"تعذر تشغيل الجلب");}finally{setBusy("");}}
  async function create(){setBusy("create");try{const response=await fetch("/api/admin/retrieval/schedules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,targetId:form.targetId||null})});if(!response.ok)throw new Error("تعذر حفظ الجدول");setForm(empty);onNotify?.("تم إنشاء جدول الجلب.");await load();}catch(value){setError(value instanceof Error?value.message:"تعذر الحفظ");}finally{setBusy("");}}
  async function toggle(schedule:Schedule){setBusy(schedule.id);await fetch(`/api/admin/retrieval/schedules/${schedule.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:!schedule.enabled})});await load();setBusy("");}
  async function remove(id:string){setBusy(id);await fetch(`/api/admin/retrieval/schedules/${id}`,{method:"DELETE"});await load();setBusy("");}
  const targetOptions=form.targetType==="source"?sources:form.targetType==="category"?categories:form.targetType==="platform"?[{id:"X",title:"إكس (X)"},{id:"Instagram",title:"إنستغرام"},{id:"TikTok",title:"تيك توك"},{id:"Snapchat",title:"سناب شات"},{id:"YouTube",title:"يوتيوب"}]:[];
  return <section className="retrieval-automation">
    <header className="resource-heading"><div><h2>الجلب الآلي واليدوي</h2><p>جدولة الأخبار والمنصات وتشغيلها عبر قواعد التحقق والتصنيف ومنع التكرار نفسها.</p></div><div className="retrieval-global-actions"><button disabled={!!busy} onClick={()=>manual("news")}><RefreshCw/> تحديث الأخبار الآن</button><button disabled={!!busy} onClick={()=>manual("social")}><RefreshCw/> تحديث منشورات المنصات الآن</button><button className="primary-btn" disabled={!!busy} onClick={()=>manual("all")}>{busy.startsWith("run:")?<Loader2 className="spin"/>:<Play/>} تحديث جميع المصادر الآن</button></div></header>
    <div className="retrieval-specific-actions"><label><span>مصدر محدد</span><select value={quickSource} onChange={(event)=>setQuickSource(event.target.value)}><option value="">اختر المصدر…</option>{sources.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><button disabled={!quickSource||!!busy} onClick={()=>manual("source",quickSource)}><RefreshCw/> تحديث هذا المصدر</button></label><label><span>تصنيف محدد</span><select value={quickCategory} onChange={(event)=>setQuickCategory(event.target.value)}><option value="">اختر التصنيف…</option>{categories.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><button disabled={!quickCategory||!!busy} onClick={()=>manual("category",quickCategory)}><RefreshCw/> تحديث هذا التصنيف</button></label></div>
    {error&&<div className="admin-error"><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}
    <div className="retrieval-layout">
      <section className="schedule-editor"><h3><Plus/> إضافة جدول</h3><div className="schedule-form">
        <label><span>اسم الجدول</span><input value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})}/></label>
        <label><span>النطاق</span><select value={form.targetType} onChange={(event)=>setForm({...form,targetType:event.target.value,targetId:""})}><option value="news">كل الأخبار</option><option value="social">كل المنصات</option><option value="all">جميع المصادر</option><option value="source">مصدر محدد</option><option value="category">تصنيف محدد</option><option value="platform">منصة محددة</option></select></label>
        {targetOptions.length>0&&<label><span>الهدف المحدد</span><select value={form.targetId} onChange={(event)=>setForm({...form,targetId:event.target.value})}><option value="">اختر…</option>{targetOptions.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label>}
        <label><span>التكرار</span><select value={form.frequency} onChange={(event)=>setForm({...form,frequency:event.target.value})}><option value="hourly">كل عدد من الساعات</option><option value="daily">يومي</option><option value="selected_days">أيام محددة</option></select></label>
        {form.frequency==="hourly"?<label><span>كل كم ساعة</span><input type="number" min="1" max="168" value={form.intervalHours} onChange={(event)=>setForm({...form,intervalHours:Number(event.target.value)})}/></label>:<label><span>وقت التنفيذ</span><input type="time" value={form.fixedTime} onChange={(event)=>setForm({...form,fixedTime:event.target.value})}/></label>}
        <label><span>المنطقة الزمنية</span><select value={form.timezone} onChange={(event)=>setForm({...form,timezone:event.target.value})}><option>Asia/Riyadh</option><option>UTC</option><option>Asia/Dubai</option><option>Africa/Cairo</option><option>Europe/London</option></select></label>
        <label><span>مسار النشر</span><select value={form.workflow} onChange={(event)=>setForm({...form,workflow:event.target.value})}><option value="review">مراجعة تحريرية</option><option value="draft">حفظ كمسودة</option><option value="publish">نشر تلقائي عند السماح</option></select></label>
        {form.frequency==="selected_days"&&<div className="weekday-picker">{days.map((day,index)=><label key={day}><input type="checkbox" checked={form.weekdays.includes(index)} onChange={()=>setForm({...form,weekdays:form.weekdays.includes(index)?form.weekdays.filter((item)=>item!==index):[...form.weekdays,index]})}/>{day}</label>)}</div>}
      </div><button className="primary-btn" disabled={busy==="create"||!form.name||((form.targetType==="source"||form.targetType==="category"||form.targetType==="platform")&&!form.targetId)} onClick={create}>{busy==="create"?<Loader2 className="spin"/>:<Plus/>} حفظ الجدول</button></section>
      <section className="schedule-list"><h3><CalendarClock/> الجداول الحالية</h3>{schedules.map((schedule)=><article key={schedule.id}><div><strong>{schedule.name}</strong><small>{targetLabel(schedule)} · {frequencyLabel(schedule)} · {workflowLabel(schedule.workflow)}</small><span>آخر تشغيل: {dateLabel(schedule.lastRunAt)} · القادم: {schedule.enabled?dateLabel(schedule.nextRunAt):"متوقف"}</span></div><div><button onClick={()=>manual(schedule.targetType,schedule.targetId||undefined,schedule.workflow)} title="تشغيل الآن"><Play/></button><button className={schedule.enabled?"toggle-on":""} onClick={()=>toggle(schedule)} disabled={busy===schedule.id}>{schedule.enabled?"مفعّل":"متوقف"}</button><button className="danger" onClick={()=>remove(schedule.id)}><Trash2/></button></div></article>)}</section>
    </div>
    <section className="retrieval-runs"><h3>صحة محولات المصادر</h3><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>المصدر</th><th>الحالة</th><th>المحول</th><th>آخر نجاح</th><th>الاستجابة</th><th>مقبول / مرفوض</th><th>أخطاء الاستخراج والصور</th></tr></thead><tbody>{health.length?health.map((item)=><tr key={item.sourceId}><td>{sources.find((source)=>source.id===item.sourceId)?.title||item.sourceId}</td><td><span className={`resource-status ${item.healthStatus==="Healthy"?"positive":item.healthStatus==="Failing"?"negative":"warning"}`}>{item.healthStatus} · {item.consecutiveFailures}</span></td><td>{item.retrievalMethod||item.adapter}</td><td>{dateLabel(item.lastSuccessAt)}</td><td>{item.responseTimeMs==null?"—":`${item.responseTimeMs} ms`}</td><td>{item.articlesAccepted} / {item.articlesRejected}</td><td>{item.extractionFailures} استخراج · {item.imageFailures} صورة · {item.httpErrors} HTTP{item.lastError?` — ${item.lastError}`:""}</td></tr>):<tr><td colSpan={7}>ستظهر صحة المصادر بعد أول جلسة بالمحرك الجديد.</td></tr>}</tbody></table></div></section>
    <section className="retrieval-runs"><h3>سجل جلسات الجلب</h3><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>البداية</th><th>المشغّل</th><th>النطاق</th><th>الحالة</th><th>المدة</th><th>النتائج</th><th>الأخطاء</th></tr></thead><tbody>{runs.slice(0,25).map((run)=><tr key={run.id}><td>{dateLabel(run.startedAt)}</td><td>{run.triggerType==="scheduled"?"مجدول":"يدوي"} · {run.actor}</td><td>{run.targetType}</td><td><span className={`resource-status ${run.status.includes("fail")?"negative":run.status==="running"?"warning":"positive"}`}>{run.status}</span></td><td>{run.durationMs==null?"—":`${(run.durationMs/1000).toFixed(1)} ث`}</td><td>{summary(run.report)}</td><td>{run.error||String((run.report.failedSources as unknown[])?.join("، ")||"—")}</td></tr>)}</tbody></table></div></section>
  </section>;
}
function dateLabel(value:string|null){return value?new Date(value).toLocaleString("ar-SA"):"لم يُشغّل";}
function targetLabel(value:Schedule){return ({news:"الأخبار",social:"المنصات",all:"الجميع",source:"مصدر",category:"تصنيف",platform:"منصة"} as Record<string,string>)[value.targetType]+(value.targetId?` · ${value.targetId}`:"");}
function frequencyLabel(value:Schedule){return value.frequency==="hourly"?`كل ${value.intervalHours} ساعة`:value.frequency==="daily"?`يوميًا ${value.fixedTime}`:`أيام محددة ${value.fixedTime}`;}
function workflowLabel(value:string){return ({review:"للمراجعة",draft:"مسودة",publish:"نشر تلقائي"} as Record<string,string>)[value]||value;}
function summary(report:Record<string,unknown>){return `${report.found||0} مسترجع · ${report.imported||0} جديد · ${report.updated||0} محدّث · ${report.published||0} منشور · ${report.invalidForReview||0} غير مكتمل · ${report.sensitiveForReview||0} حساس · ${report.duplicates||0} مكرر`;}
