"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Bell, Database, Gauge, Globe2, Home, Loader2, Mail, Palette, RefreshCcw, Save, Send, Settings2, ShieldCheck } from "lucide-react";

type SettingField={key:string;label:string;type?:"text"|"email"|"url"|"number"|"select"|"checkbox"|"color"|"textarea";options?:string[];required?:boolean;hint?:string};
type Section={label:string;description:string;icon:typeof Settings2;fields:SettingField[];defaults:Record<string,unknown>};
const sections:Record<string,Section>={
  general:{label:"الإعدادات العامة",description:"هوية الموقع واللغة والمنطقة الزمنية وبيانات التواصل.",icon:Globe2,fields:[{key:"siteName",label:"اسم الموقع",required:true},{key:"tagline",label:"الوصف المختصر",required:true},{key:"siteUrl",label:"رابط الموقع",type:"url",required:true},{key:"contactEmail",label:"بريد التواصل",type:"email",required:true},{key:"phone",label:"رقم الهاتف"},{key:"language",label:"اللغة الافتراضية",type:"select",options:["العربية","English"]},{key:"timezone",label:"المنطقة الزمنية",type:"select",options:["Asia/Riyadh","UTC","Asia/Dubai"]},{key:"dateFormat",label:"تنسيق التاريخ",type:"select",options:["هجري وميلادي","ميلادي","هجري"]}],defaults:{siteName:"المختصر",tagline:"أهم ما تحتاج معرفته",siteUrl:"http://localhost:3000",contactEmail:"info@almukhtasar.test",phone:"",language:"العربية",timezone:"Asia/Riyadh",dateFormat:"هجري وميلادي"}},
  appearance:{label:"الهوية البصرية",description:"الشعار والألوان والخط والوضع الليلي واتجاه الواجهة.",icon:Palette,fields:[{key:"logoUrl",label:"رابط الشعار",type:"url"},{key:"faviconUrl",label:"رابط الأيقونة",type:"url"},{key:"primaryColor",label:"اللون الأساسي",type:"color"},{key:"navyColor",label:"اللون الثانوي",type:"color"},{key:"fontFamily",label:"الخط",type:"select",options:["Tahoma","Noto Kufi Arabic","IBM Plex Sans Arabic","Cairo"]},{key:"direction",label:"اتجاه الواجهة",type:"select",options:["RTL","LTR","تلقائي حسب اللغة"]},{key:"darkMode",label:"السماح بالوضع الليلي",type:"checkbox"},{key:"defaultDark",label:"الوضع الليلي افتراضيًا",type:"checkbox"}],defaults:{logoUrl:"",faviconUrl:"",primaryColor:"#e83d4f",navyColor:"#102a43",fontFamily:"Tahoma",direction:"RTL",darkMode:true,defaultDark:false}},
  homepage:{label:"الصفحة الرئيسية",description:"الأقسام الظاهرة وترتيب الأخبار والترويسة والتذييل.",icon:Home,fields:[{key:"heroCount",label:"عدد الأخبار البارزة",type:"number",required:true},{key:"briefCount",label:"عدد عناصر مختصر اليوم",type:"number",required:true},{key:"autoFeatured",label:"اختيار الأخبار البارزة تلقائيًا",type:"checkbox"},{key:"showTrending",label:"إظهار الأكثر تداولًا",type:"checkbox"},{key:"showEditorPicks",label:"إظهار مختارات المحرر",type:"checkbox"},{key:"showVideos",label:"إظهار الفيديوهات",type:"checkbox"},{key:"showNewsletter",label:"إظهار النشرة البريدية",type:"checkbox"},{key:"headerNotice",label:"نص الشريط العلوي",type:"textarea"},{key:"footerText",label:"نص التذييل",type:"textarea"}],defaults:{heroCount:4,briefCount:7,autoFeatured:true,showTrending:true,showEditorPicks:true,showVideos:true,showNewsletter:true,headerNotice:"تحديث مستمر لأهم التطورات من المصادر الرسمية والموثوقة",footerText:"منصة محتوى ذكية تجمع وتتحقق وتلخص أهم الأخبار."}},
  light_version:{label:"النسخة الخفيفة",description:"التحكم في النسخة السريعة وتصنيفاتها وكثافة الأخبار.",icon:Gauge,fields:[{key:"enabled",label:"تفعيل النسخة الخفيفة",type:"checkbox"},{key:"defaultMode",label:"النسخة الافتراضية",type:"select",options:["النسخة الكاملة","النسخة الخفيفة","الخفيفة على الجوال فقط"]},{key:"desktopCount",label:"عدد العناوين لكل تصنيف على سطح المكتب",type:"number",required:true},{key:"mobileCount",label:"عدد العناوين لكل تصنيف على الجوال",type:"number",required:true},{key:"pageSize",label:"عدد الأخبار في صفحة التصنيف",type:"number",required:true},{key:"categories",label:"التصنيفات الظاهرة وترتيبها",type:"textarea",hint:"تصنيف واحد في كل سطر. احذف أي تصنيف لإخفائه واسحب ترتيبه بتحرير ترتيب الأسطر."},{key:"showTime",label:"إظهار وقت النشر",type:"checkbox"},{key:"showBadges",label:"إظهار شارات عاجل ومحدّث",type:"checkbox"}],defaults:{enabled:true,defaultMode:"النسخة الكاملة",desktopCount:6,mobileCount:4,pageSize:20,categories:"السياسة\nالاقتصاد\nالمجتمع\nالرياضة\nالتقنية\nالذكاء الاصطناعي\nالصحة\nالثقافة\nالسيارات\nالسفر\nالتعليم",showTime:true,showBadges:true}},
  homepage_supply:{label:"إمداد أخبار الصفحة",description:"حدود المخزون المنشور والاحتياطي وحداثة وجودة المواد.",icon:RefreshCcw,fields:[{key:"minimumHomepagePosts",label:"الحد الأدنى لأخبار الصفحة",type:"number",required:true},{key:"minimumPostsPerCategory",label:"الحد الأدنى لكل تصنيف",type:"number",required:true},{key:"minimumReservePosts",label:"الحد الأدنى للمخزون الاحتياطي",type:"number",required:true},{key:"maximumPostAgeHours",label:"أقصى عمر مقبول بالساعات",type:"number",required:true},{key:"minimumSourceReliability",label:"الحد الأدنى لموثوقية المصدر",type:"number",required:true},{key:"minimumCompletenessScore",label:"الحد الأدنى لاكتمال المحتوى (من 8)",type:"number",required:true},{key:"urgentRetrievalEnabled",label:"تشغيل جلب عاجل عند النقص",type:"checkbox"},{key:"emergencyAutoPublish",label:"نشر أول مادة سليمة لاستعادة الإمداد",type:"checkbox"}],defaults:{minimumHomepagePosts:5,minimumPostsPerCategory:2,minimumReservePosts:10,maximumPostAgeHours:8760,minimumSourceReliability:85,minimumCompletenessScore:6,urgentRetrievalEnabled:true,emergencyAutoPublish:true}},
  publishing:{label:"إعدادات النشر",description:"الموافقات والجدولة والمحتوى الحساس والظهور والتحديثات.",icon:Send,fields:[{key:"defaultStatus",label:"الحالة الافتراضية",type:"select",options:["مسودة","بانتظار المراجعة","معتمد"]},{key:"manualApproval",label:"اشتراط الموافقة اليدوية",type:"checkbox"},{key:"sensitiveReview",label:"مراجعة إلزامية للمحتوى الحساس",type:"checkbox"},{key:"minTrust",label:"الحد الأدنى للموثوقية",type:"number",required:true},{key:"autoPublish",label:"السماح بالنشر التلقائي للمحتوى الآمن",type:"checkbox"},{key:"retainVersions",label:"الاحتفاظ بجميع الإصدارات",type:"checkbox"},{key:"showAiDisclosure",label:"إظهار مساهمة الذكاء الاصطناعي",type:"checkbox"},{key:"updateTimestamp",label:"تحديث وقت آخر تعديل تلقائيًا",type:"checkbox"},{key:"defaultChannels",label:"قنوات الظهور الافتراضية",type:"textarea",hint:"مثال: الموقع، التطبيق، الإشعارات"}],defaults:{defaultStatus:"مسودة",manualApproval:true,sensitiveReview:true,minTrust:80,autoPublish:false,retainVersions:true,showAiDisclosure:true,updateTimestamp:true,defaultChannels:"الموقع، التصنيفات"}},
  communications:{label:"البريد والإشعارات",description:"بيانات المرسل وقواعد الإرسال والتنبيهات الإدارية.",icon:Mail,fields:[{key:"senderName",label:"اسم المرسل",required:true},{key:"senderEmail",label:"بريد المرسل",type:"email",required:true},{key:"replyTo",label:"بريد الرد",type:"email"},{key:"dailyLimit",label:"الحد اليومي للإرسال",type:"number"},{key:"adminAlerts",label:"إشعارات أخطاء النظام",type:"checkbox"},{key:"reviewAlerts",label:"إشعارات مهام المراجعة",type:"checkbox"},{key:"sourceFailureAlerts",label:"تنبيه عند فشل المصدر",type:"checkbox"},{key:"quietHours",label:"ساعات عدم الإزعاج"}],defaults:{senderName:"المختصر",senderEmail:"news@almukhtasar.test",replyTo:"support@almukhtasar.test",dailyLimit:10000,adminAlerts:true,reviewAlerts:true,sourceFailureAlerts:true,quietHours:"23:00 - 06:00"}},
  storage:{label:"التخزين والنسخ الاحتياطي",description:"التخزين السحابي والاحتفاظ بالملفات والنسخ والصيانة.",icon:Database,fields:[{key:"storageProvider",label:"مزود التخزين",type:"select",options:["محلي","S3-compatible","Google Cloud Storage"]},{key:"cdnUrl",label:"رابط CDN",type:"url"},{key:"maxUploadMb",label:"أقصى حجم للرفع (MB)",type:"number"},{key:"imageOptimization",label:"تحسين الصور تلقائيًا",type:"checkbox"},{key:"preferredFormat",label:"صيغة الصور",type:"select",options:["WebP","AVIF","تلقائي"]},{key:"backupSchedule",label:"جدول النسخ",type:"select",options:["يومي","أسبوعي","يدوي"]},{key:"retentionDays",label:"مدة الاحتفاظ بالأيام",type:"number"},{key:"maintenanceMode",label:"وضع الصيانة",type:"checkbox"}],defaults:{storageProvider:"محلي",cdnUrl:"",maxUploadMb:20,imageOptimization:true,preferredFormat:"WebP",backupSchedule:"يومي",retentionDays:30,maintenanceMode:false}},
  security:{label:"الأمن والوصول",description:"الجلسات والمصادقة الثنائية وسجلات الإجراءات والحماية.",icon:ShieldCheck,fields:[{key:"require2fa",label:"فرض المصادقة الثنائية للمديرين",type:"checkbox"},{key:"sessionMinutes",label:"مدة الجلسة بالدقائق",type:"number"},{key:"maxAttempts",label:"محاولات الدخول المسموحة",type:"number"},{key:"auditRetention",label:"مدة حفظ سجل التدقيق بالأيام",type:"number"},{key:"allowedFileTypes",label:"أنواع الملفات المسموحة",type:"textarea"},{key:"ipAllowlist",label:"عناوين IP المسموحة (اختياري)",type:"textarea"},{key:"notifySensitiveChanges",label:"تنبيه عند تغيير إعداد حساس",type:"checkbox"}],defaults:{require2fa:true,sessionMinutes:60,maxAttempts:5,auditRetention:365,allowedFileTypes:"jpg, jpeg, png, webp, avif, mp4, pdf",ipAllowlist:"",notifySensitiveChanges:true}}
};

export default function SettingsWorkspace({onNotify}:{onNotify?:(message:string)=>void}){const [active,setActive]=useState("general"),[values,setValues]=useState<Record<string,unknown>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");const section=sections[active];
  useEffect(()=>{let cancelled=false;setLoading(true);setError("");fetch(`/api/admin/settings?section=${active}`).then(response=>response.json()).then(result=>{if(!cancelled)setValues({...section.defaults,...(result.data?.[0]?.value||{})})}).catch(()=>!cancelled&&setError("تعذر تحميل الإعدادات")).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}},[active,section.defaults]);
  const changed=useMemo(()=>JSON.stringify(values)!==JSON.stringify(section.defaults),[values,section.defaults]);
  function change(field:SettingField,value:unknown){setValues(current=>({...current,[field.key]:value}));}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({section:active,value:values})});if(!response.ok)throw new Error();onNotify?.(`تم حفظ ${section.label}`);}catch{setError("تعذر حفظ الإعدادات");}finally{setSaving(false)}}
  async function testMail(){onNotify?.("تم إرسال رسالة اختبار تجريبية إلى بريد المدير");}
  return <div className="settings-workspace"><aside className="settings-nav">{Object.entries(sections).map(([key,item])=>{const Icon=item.icon;return <button key={key} className={active===key?"active":""} onClick={()=>setActive(key)}><Icon/><span><b>{item.label}</b><small>{item.description}</small></span></button>})}</aside><section className="settings-content"><header><div><span className="settings-icon">{(() => {const Icon=section.icon;return <Icon/>})()}</span><div><h2>{section.label}</h2><p>{section.description}</p></div></div>{active==="communications"&&<button className="secondary-admin-btn" onClick={testMail}><Bell/> اختبار الإرسال</button>}</header>{error&&<div className="admin-error">{error}</div>}{loading?<div className="resource-state"><Loader2 className="spin"/> جارٍ تحميل الإعدادات...</div>:<form onSubmit={save}><div className="settings-form-grid">{section.fields.map(field=><label key={field.key} className={field.type==="textarea"?"full-field":""}><span>{field.label}{field.required&&<b>*</b>}</span>{field.hint&&<small>{field.hint}</small>}{field.type==="select"?<select value={String(values[field.key]??field.options?.[0]??"")} onChange={event=>change(field,event.target.value)}>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:field.type==="textarea"?<textarea rows={4} value={String(values[field.key]??"")} onChange={event=>change(field,event.target.value)}/>:field.type==="checkbox"?<span className="settings-switch"><input type="checkbox" checked={Boolean(values[field.key])} onChange={event=>change(field,event.target.checked)}/><i/><em>{values[field.key]?"مفعّل":"معطّل"}</em></span>:<input type={field.type||"text"} required={field.required} value={String(values[field.key]??"")} onChange={event=>change(field,field.type==="number"?Number(event.target.value):event.target.value)}/>}</label>)}</div><footer className="settings-footer"><div><small>تُسجل جميع التعديلات في سجل التدقيق.</small>{changed&&<span>توجد تغييرات غير محفوظة</span>}</div><button type="button" onClick={()=>{setValues(section.defaults);onNotify?.("تمت استعادة القيم الافتراضية محليًا")}}><RefreshCcw/> استعادة الافتراضي</button><button className="primary-btn" disabled={saving}><Save/>{saving?"جارٍ الحفظ...":"حفظ الإعدادات"}</button></footer></form>}</section></div>}
